### ISSUE TITLE
Failing build on ember-cli 2.7.0

### ISSUE THREAD

**Issue by vmalloc** [altrim/ember-cli-tooltipster#26]
Tried upgrading to the latest version (from 0.1), and getting

```
route-recognizer#0.1.11 bower_components/route-recognizer
⠴ BuildingThe Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/rot/workspace/src/opensource/v/backslash/webapp/tmp/source_map_concat-input_base_path-t4T7aSJH.tmp/0/bower_components/tooltipster/dist/js/tooltipster.bundle.min.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ConcatWithMaps (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-concat/concat.js:24:17)
    at module.exports (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/ember-cli/lib/broccoli/ember-app.js:368:10)
    at EmberApp._concatFiles (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/ember-cli/lib/broccoli/ember-app.js:381:15)
    at EmberApp.javascript (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1252:12)
    at EmberApp.toArray (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1604:10)
    at EmberApp.toTree (/Users/rot/workspace/src/opensource/v/backslash/webapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
    at module.exports (/Users/rot/workspace/src/opensource/v/backslash/webapp/ember-cli-build.js:54:26)
```

**Comment by altrim** [comment]
Which version of `tooltipster` you have specified in `bower.json`? The addon currently works with `4.1.2`. Make sure you have installed that version of tooltipster.

**Comment by vmalloc** [comment]
I had 3.3.0. Going to upgrade and check again. Thanks!
